### ISSUE TITLE
Read misorientation 

### ISSUE THREAD

**Issue by kudasonya** [epi2me-labs/pychopper#1]
Hello, I have seen a similar issue submitted to the old pychopper repo and have tried running `seqkit seq -Q 7`  prior to running pychopper, however I am still seeing some mis-oriented reads. I am also wondering if this filter cutoff curve looks right as there doesn't seem to be a clear q peak like in the example. 
```
Total fastq records in input file: 26776641
Tuning the cutoff parameter (q) on 10118 sampled reads (0.0%) passing quality filters (Q >= 7.0).
Input reads failing mean quality filter (Q < 7.0): 0 (0.00%)
Output fragments failing length filter (length < 50): 0
-----------------------------------
Reads with two primers:	76.94%
Rescued reads:		6.60%
Unusable reads:		16.47%
```
![pychopper_filter](https://user-images.githubusercontent.com/97608186/178471455-cc540e0f-2d1f-4083-b47d-871d82e81d7c.png)

**Comment by cjw85** [comment]
@kudasonya Can you give details of the sequencing kit and basecaller used to generate your data. After that, @nrhorner should be able to follow up.

**Comment by kudasonya** [comment]
Hello @cjw85, so the VNP and SSP primers were from the SQK-PCS109 kit, sequencing done using SQK-LSK109 kit, Guppy was used for basecalling. After that I merged all the .fastq files.

**Comment by nrhorner** [comment]
Hi @kudasonya. Sorry for the late reply. 

Could you send me the command you used to run pychopper. Also if you are able to share your data, could you sample 100k reads or so and send here for me to test:  https://nanoporetech.box.com/s/v070yde9n1oam69v7fnysykqgvnrfh93

**Comment by cjw85** [comment]
Closing through lack of response.
