### ISSUE TITLE
Incorrect classification of reads in multiplexed samples

### ISSUE THREAD

**Issue by matthew-valentine** [epi2me-labs/pychopper#10]
We have run pychopper a lot on our ONT data, on both singleplex and multiplexed samples, and have come across some strange behaviour when classifying reads in a multiplex fast file. All files I am talking about are available at: https://riken-share.box.com/s/9qxqufb0enhbpwl0qnhcjv5wrqknghae

For multiplexed reads, we basically ran pychopper twice with the edlib mode to work with out custom primers, giving information on both primers in the fasta (primer_index1+2.fas) but only a single config file at a time (e.g. primer_config_index1.txt). We filtered the output fastq files to remove those reads that were classified in both runs. A sort of ad hoc demultiplexing and FL classification combined (or so we thought). However, we noticed some reads that in the raw sequence  matched one index perfectly, but they were classified as the other index. This seemed to be a problem specific to the multiplex samples we have, so we did some testing by making some pseudo-multiplexed files by concatenating two singleplex samples. Sure enough, the problem became apparent. 

Allow me to illustrate with a specific example from the test input fastq (contains just 1000 reads): read ID 00001200-fd9b-4aa5-ad62-3acfffcc0431. Looking at the alignment file for the pychopper run looking for alignments to index 1 (simplified below), we can see that for the region 29-90 there is alignment for both index 1 and index 2, but index 2 has a lower score so this read is put in the unclassified fastq file. On the original singleplex sample this read was correctly classified as being a full length read with index 1 sequence.

<pre>00001200-fd9b-4aa5-ad62-3acfffcc0431 29      90      VNP-index1      12      +
00001200-fd9b-4aa5-ad62-3acfffcc0431 29      90      VNP-index2      3       +
00001200-fd9b-4aa5-ad62-3acfffcc0431 973     1041    SSP     3       -</pre>

Looking at the actual region the VNP is aligned to (below), the sequence is an identical match to the VNP-index1 sequence, while the 24 base sequence specific to each index (in bold) is completely different in VNP-index2 and so we would expect a much higher edit distance for alignment. And further, we wouldn't expect such a high score for VNP-index1, since the only difference is 4 less T bases in the read sequence compared with the primer.

<pre>SEQUENCE:  GAGATGTCTCGTGGGCTCGG<b>CACAAAGACACCGACAACTTTCTT</b>CTACGTTTTTTTTTTTT
INDEX1:    GAGATGTCTCGTGGGCTCGG<b>CACAAAGACACCGACAACTTTCTT</b>CTACGTTTTTTTTTTTTTTTT
INDEX2:    GAGATGTCTCGTGGGCTCGG<b>ACAGACGACTACAAACGGAATCGA</b>CTACGTTTTTTTTTTTTTTTT</pre>

We thought maybe it would be something to do with the base quality, but editing this didn't seem to have any effect on the output so I'm guessing it isn't taken into account anyway? Any idea why we are getting these misclassified reads, or why pychopper is giving better alignment scores to an index that is a much worse match?

Thanks,
Matthew

**Comment by cjw85** [comment]
Hi @matthew-valentine,

I apologise that no one replied here. Did you resolve your issues?
