### ISSUE TITLE
Progress halts without error message, have left it for 10+ hours

### ISSUE THREAD

**Issue by tewdwr** [epi2me-labs/pychopper#13]
I’m using pychopper with custom primers in edlib mode.

The command I use is:

pychopper -b ./adaptors.fa -c ./config.txt -r ./pychopper_report.pdf -u ./pychopper_unclassified.fastq -l ./pychopper_len_failed.fastq -w ./pychopper_rescued.fastq -S ./pychopper_stats.txt -A ./pychopper_alignmentScores.txt -t 32 -m edlib ../qscore7.fastq.gz ./pychopper_output.fastq

It goes through the auto tuning process (threshold of 0.557, which corresponds to 84% of reads), and then starts the orientation and trimming process as expected. The output files are as expected, the reads are orientated correctly and the adapters are trimmed, most of the reads are in the output fastq, some in the unclassified, a little less in the rescued, and only a handful in the too short fastq. So far so good. After having run it a few times the progress just halts (without a suggestion as to why lay caused it), once at 3% progress, once at 95% progress, once at 24% progress. I’ve left it in these states for hours and it doesn’t seem like it’ll resume. The fastq files are not being updated during this time. No error message comes up.

I am considering grabbing the read IDs of the reads that are in the pychopper output fastq files, and remove those from the input fastq and keep rerunning pychopper like this until all my reads have been processed. But of course any help to get it work all the way through would be much appreciated. I am also using hammerpede to make an HMM model and will try pychopper in hmm mode, I’m hoping that this will somehow allow pychopper to run through to the end

**Comment by nrhorner** [comment]
Hi @tewdwr 

This could be related to https://github.com/epi2me-labs/pychopper/issues/11.
This user reports using `-B 10000` to lower batch size worked in their case. 

I will look into this further.

**Comment by tewdwr** [comment]
> Hi @tewdwr
> 
> This could be related to #11. This user reports using `-B 10000` to lower batch size worked in their case.
> 
> I will look into this further.

Sorry, I missed that, and thanks for the quick reply. I'm giving it a shot now, so far so good. I'll let you know the outcome

**Comment by nrhorner** [comment]
Hi @tewdwr thanks for the update, that's very useful. I'll look into this shortly.

**Comment by nrhorner** [comment]
Hi @tewdwr I'd be interested to know if you still get this issue with the latest release. I'm not able to recreate.

**Comment by nrhorner** [comment]
Closed due to lack of response.
