### ISSUE TITLE
Dorado and pychopper

### ISSUE THREAD

**Issue by rlowe-altoslabs** [epi2me-labs/pychopper#16]
At present I keep getting " 0% of the reads classified" when using FASTQ derived from a dorado basecall. My understanding is it doesn't do any adapter trimming as confirmed here: https://github.com/nanoporetech/dorado/issues/123

What is the solution or is dorado not compatible with pychopper?

**Comment by rlowe-altoslabs** [comment]
Ok so the issue is that this doesn't support spaces in the read name when using `nhmmscan`. So say you have a fastq file with

```
@name1 something else
```

`nhmmscan` will report hits for `name1` but matching to the name id `name1 something else` won't work. Will add a fix

**Comment by nrhorner** [comment]
Hi @rlowe-altoslabs 

Thanks for raising this issues. It should be fixed in the latest version (v0.2.6). Please could you give that a try.
