### ISSUE TITLE
issues with the unclassified file

### ISSUE THREAD

**Issue by VandaLovejoy** [epi2me-labs/pychopper#17]
Hello,
In the unclassified file, I find sequences that have the two custom primers that I have input and I do not understand why they are not classified and the orientation not determined.
For example I get this sequence in the unclassified file:
TACTTCGTTCAGTTACGTACTAAGGTTAAAAGGTTACACAAACCCTGGACAAGCAGCACCT**TTTCTGTTGGTGCTGATATTGC**TGGGGGCGCCGGCGGCTTTGGTGACTCTAGATAACCTCGGGCCGATCGCACGCCCCCGTGGCGGCGACGACCCATTCGAACGTCTGCCCTATCAACTTTCGATGGTAGTCGCCATTCCATGGTGACCACAGGTGACGGGGAATCGGGGTTCGATTCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGG**CTGTAGGCACCATCAAT**GGGTGCTGCTTGTCCAGGGTTTGTGTAACCTTTTAACCTTAGCAATACGTAACTGA

This is my command line: 
`pychopper -b custom_primers.fa -c primer_config.txt -t 20 -r sample_report_pychopper.pdf -m edlib -S sample_stats_pychopper.tsv -u sample_unclassified_pychopper.fastq -w sample_rescued_pychopper.fastq sample_merge.fastq sample_full_pychopper.fastq`

This is my custom primer:
 >SSP
TTTCTGTTGGTGCTGATATTGC
 >BanOne
ATTGATGGTGCCTACAG

and my config file
+:SSP,-BanOne|-:BanOne,-SSP

Thank you!

**Comment by nrhorner** [comment]
Hi @VandaLovejoy 

Did you miss the '>' from your primer fasta entries?

It works for me when customer_primers.fa looks like 

```
 >SSP
TTTCTGTTGGTGCTGATATTGC
 >BanOne
 ATTGATGGTGCCTACAG
```
Thanks,

Neil

**Comment by nrhorner** [comment]
Assuming this is fixed as there has been no reply
