### ISSUE TITLE
Pandas df.append was removed from version 2.0

### ISSUE THREAD

**Issue by ChristophBoerlin** [epi2me-labs/pychopper#18]
After introducing a deprecation warning for the method df.append() in Pandas version 1.4.0 it has now been removed in version 2.0, meaning that no report can be produced and pychopper will fail.

Error is in scripts/pychopper.py line 542:
`stdf = stdf.append(pd.DataFrame(tune_df))
`
The new way to append a df to an existing df is with using pd.concat (see https://pandas.pydata.org/pandas-docs/version/1.5/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append)

Quick fix would be to fix the Pandas version to <2

**Comment by zhenyuan992** [comment]
@ChristophBoerlin 
are you able to give me some sample data for me to test?
i have made some changes, if u know how to pull the correct branch, you can test it yourself.

**Comment by nrhorner** [comment]
Thanks for highlighting this. I'll get this fixed an released ASAP

**Comment by zhenyuan992** [comment]
@nrhorner this is solved in PR #19

**Comment by nrhorner** [comment]
@zhenyuan992 code changes must go through our CI before being released to github so I won't be able to merge your PR, but I will add your change to to the next release. Thanks

**Comment by zhenyuan992** [comment]
@nrhorner sure thing!

**Comment by NanoCoreUSA** [comment]
I manually changed the pychopper.py as described to fix this error, however just wanted to point out that this wasn't the only fix required. After changing the problematic line from 'append' to 'concat', I also received the following error:

```
Traceback (most recent call last):
  File "/home/justin/Miniconda3/envs/pychopper/bin/pychopper", line 10, in <module>
    sys.exit(main())
  File "/home/justin/Miniconda3/envs/pychopper/lib/python3.10/site-packages/pychopper/scripts/pychopper.py", line 542, in main
    stdf = pd.concat([stdf,tune_df])
  File "/home/justin/Miniconda3/envs/pychopper/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 372, in concat
    op = _Concatenator(
  File "/home/justin/Miniconda3/envs/pychopper/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 462, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'collections.OrderedDict'>'; only Series and DataFrame objs are valid
```

I believe this occurred because 'tune_df' is not actually a DataFrame... I fixed it by adding the following line before the concatenation:

`tune_df = pd.DataFrame(tune_df)`

Thanks for the fix!

**Comment by nrhorner** [comment]
@zhenyuan992 @NanoCoreUSA @ChristophBoerlin 

The latest version has now been released (v2.7.3) which fixes the pandas v2.0 issues. Thanks

**Comment by NanoCoreUSA** [comment]
Thanks for the quick fix! The conda channel hasn't updated with the newest version yet, is there a simple way to manually install? I feel like I could just download the repo and run the make command but not sure if this would mess up the conda environment.

**Comment by nrhorner** [comment]
Sorry about that. The conda repository has changed and there were some issue relating to that.

Could you try: installing with `conda install -c nanoporetech -c conda-forge -c bioconda "nanoporetech::pychopper"` 

I need to update the README instructions too,
