### ISSUE TITLE
How can I install pychopper with source code?

### ISSUE THREAD

**Issue by mianlee** [epi2me-labs/pychopper#23]
Hello 

I had some issues to install pychopper with conda (internet issue).  How can  install pychopper from source code?

Thank you so much !

Mian

**Comment by cjw85** [comment]
Hi @mianlee,

You will need the internet to access the source code, and write issues on GitHub. Could you please elaborate on your conda install problems.

**Comment by cjw85** [comment]
Closing through lack of response.
