### ISSUE TITLE
How to combine pychopper with other adapters-removing tool?

### ISSUE THREAD

**Issue by qiuyixmm** [epi2me-labs/pychopper#25]
Hello,
     I want to obtain oriented and trimmed full-length Nanopore cDNA reads without adapter sequences. [Porechop](https://github.com/rrwick/Porechop) is a tool for finding and removing adapters, which I want to use for my Nanopore cDNA reads. I am not sure which tools (pychopper or porechop) I should use first to process my Nanopore cDNA reads. Would you like to give me some advice? 
      BTW, is it necessary to remove adapter sequences when raw Nanopore cDNA reads are processed by pychopper?
      Thanks!

**Comment by nrhorner** [comment]
Hi @qiuyixmm 

Pychopper will generate adapter-trimmed reads for you; there should be no need to run Porechop as well.

Please try it out and post another message if you encounter any problems.
