### ISSUE TITLE
About Using User's Own Primer Sequences

### ISSUE THREAD

**Issue by liuyh99** [epi2me-labs/pychopper#26]
Hello, I want to use my own primer sequence to identify full field reads when using pychopper. I used - b and - c to specify my own primer sequence, referring to the standard format (file content is as follows), but it still appears when running the program using the default PCS109 primer sequence. How can I solve this problem?

'''my primer:
>VNP
AAAAAAAAAAAAAAAAAAAAGAAGATAGAGCGACAGGCAAGT
>SSP
TTTCTGTTGGTGCTGATATTGCTGGG
configurations:
+:SSP,-VNP|-:VNP,-SSP'''

**Comment by nrhorner** [comment]
Hi @liuyh99 

When specifying your own primers using -b, unfortunately you will still receive the following message `Using kit: PCS109`, but your custom primers will be used. This is confusing and I will get that fixed.

**Comment by nrhorner** [comment]
Hi @liuyh99 

This issue should now be fixed in v2.7.7. Please get in touch if you have any more issues.

**Comment by liuyh99** [comment]
Okay, thank you for the update.
