### ISSUE TITLE
Implications of the change of license on distribution by Debian

### ISSUE THREAD

**Issue by pgrt** [epi2me-labs/pychopper#27]
Dear Maintainers,

I am writing as a member of the team maintaining pychopper in Debian.

We saw that commit 445bde1 changed the license of pychopper, mainly (as we see) limiting the use of the software to research purposes.
I am sure you have great reasons to do so.
However, we would like to draw your attention on the fact that this change makes it impossible for Debian to ship version 2.7.4 of pychopper as restricting the field of endeavour is not compatible with the Debian Free Software Guidelines.
This also affects the derivatives of Debian and possibly other distributions -- I don't know.

It would be great for the distribution of pychopper if the change you made could be reverted. Yet, once again, I trust you have reasons for it but I want to be sure the distribution concern is taken into consideration.

Best regards,
Pierre

**Comment by cjw85** [comment]
The change will not be reverted.

We do not believe this adversely affects distribution of our software to relevant parties because we create packages for both PyPI and conda. The latter of these in particular has become the de facto standard for distribution of bioinformatics software.

**Comment by pgrt** [comment]
Hello,

Thanks for looking at my question. I understand and of course this is up to you.

I expect the new limitation of use to, still, limit the freedom of users through PyPI and conda though. But maybe I am overlooking something here.

Have a great Sunday :)

Pierre

**Comment by tmancill** [comment]
> The change will not be reverted.
> 
> We do not believe this adversely affects distribution of our software to relevant parties because we create packages for both PyPI and conda. The latter of these in particular has become the de facto standard for distribution of bioinformatics software.

Hmm... PyPI and conda are means of distribution, which is an orthogonal concern to @pgrt 's question is about the fields of endeavor permitted by the license.

By the way, the top-level project [README.md](https://github.com/epi2me-labs/pychopper/blob/master/README.md) still claims an MPL 2.0 license as per [this commit](https://github.com/epi2me-labs/pychopper/commit/1ac452761675e85212f82dec93aa5d46e009da9c).

**Comment by cjw85** [comment]
The OPs concern was that a pychopper package should not  now be distributed through the Debian repository due to the Debian imposed guidelines. That is a matter entirely up to the repository maintainers: they are free to create and uphold rules which align with their values.

We do not believe the change of license adversely affects the ability of the target audience to use our software.

If you have any other questions please contact legal@nanoporetech.com.
