### ISSUE TITLE
Error with 'append' while running pychopper

### ISSUE THREAD

**Issue by majdabdul** [epi2me-labs/pychopper#28]
Hello,

I encountered the following wrror while running pychopper on one of my samples: 

`$ pychopper ../PAK96837/01_raw_reads/10890_Control_IR_rep3_pass.fastq.gz pychopped/cont_ir_rep3_pychopped.fastq.gz
Using kit: PCS109
Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
Counting fastq records in input file: ../PAK96837/01_raw_reads/10890_Control_IR_rep3_pass.fastq.gz
Total fastq records in input file: 2304022
Tuning the cutoff parameter (q) on 10027 sampled reads (0.4%) passing quality filters (Q >= 7.0).
Optimizing over 30 cutoff values.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [10:08<00:00, 20.02s/it]
Best cutoff (q) value is 0.3448 with 86% of the reads classified.
Processing the whole dataset using a batch size of 288002:
100%|████████████████████████████████████████████████████████████████████████████████████████| 2304022/2304022 [1:24:11<00:00, 456.11it/s]
Finished processing file: ../PAK96837/01_raw_reads/10890_Control_IR_rep3_pass.fastq.gz
Input reads failing mean quality filter (Q < 7.0): 0 (0.00%)
Output fragments failing length filter (length < 50): 0
Traceback (most recent call last):
  File "/data/donc-panc-cancer-biomarker/ball5492/pychopper_env/bin/pychopper", line 10, in <module>
    sys.exit(main())
  File "/data/donc-panc-cancer-biomarker/ball5492/pychopper_env/lib/python3.10/site-packages/pychopper/scripts/pychopper.py", line 542, in main
    stdf = stdf.append(pd.DataFrame(tune_df))
  File "/data/donc-panc-cancer-biomarker/ball5492/pychopper_env/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?`

As far as I can tell from Googling, it's an issue with Pandas versioning. I have version 2.0.2 (the latest version, as of writing this).

Can you please help me figure out how to fix it?

Thanks!

**Comment by majdabdul** [comment]
> Hi @majdabdul You're right; pandas >=2.0 has done away with DataFrame.append() This is fixed in the latest Pychopper version (v0.2.5). Please try that.

Thanks @nrhorner. Updating Pychopper got rid of this error indeed! But now I see this message:
`Finished processing file: /data/donc-panc-cancer-biomarker/ball5492/long/PromethIONRuns/combined/10890_Control_IR_rep1_combined_pass.fastq.gz
Input reads failing mean quality filter (Q < 7.0): 0 (0.00%)
Output fragments failing length filter (length < 50): 0
/data/donc-panc-cancer-biomarker/ball5492/pychopper_env/lib/python3.10/site-packages/pychopper/scripts/pychopper.py:184: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  found, rescue, unusable = float(rs.loc[rs.Name == "Primers_found", ].Value), float(rs.loc[rs.Name == "Rescue", ].Value), float(rs.loc[rs.Name == "Unusable", ].Value)
/data/donc-panc-cancer-biomarker/ball5492/pychopper_env/lib/python3.10/site-packages/pychopper/scripts/pychopper.py:186: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  umi_detected = float(rs_stats.loc[rs_stats.Name == "Umi_detected", ].Value)
/data/donc-panc-cancer-biomarker/ball5492/pychopper_env/lib/python3.10/site-packages/pychopper/scripts/pychopper.py:187: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  umi_detected_final = float(rs_stats.loc[rs_stats.Name == "Umi_detected_final", ].Value)`

I'm not sure if it's related to the update, but can I assume that it doesn't affect the final output?

**Comment by nrhorner** [comment]
Hi @majdabdul 
This is a warning from a third party library, which will have no affect on the results. This will be addressed in the next release. 

Could I ask you to use v0.2.6 now though as there was an introduced into v0.2.5 where things break when using the `-m edlib` option.

Thanks

**Comment by majdabdul** [comment]
/

**Comment by majdabdul** [comment]
> Hi @majdabdul This is a warning from a third party library, which will have no affect on the results. This will be addressed in the next release.
> 
> Could I ask you to use v0.2.6 now though as there was an introduced into v0.2.5 where things break when using the `-m edlib` option.
> 
> Thanks

Wow @nrhorner, you work fast! Will update, thanks!
