### ISSUE TITLE
low number of usable reads with DCS109

### ISSUE THREAD

**Issue by kallekarlhugo** [epi2me-labs/pychopper#3]
Hi, 
We have just finished our first run of direct cDNA sequencing on our minion using the DCS109 library kit. 

After basecalling with the guppy HAC we have tried running pychopper with the default settings, (as well as using the -x DCS109 option).

pychopper -r report.pdf -u fb1_unclassified.fq -w fb1_rescued.fq fb1_hac.fq.gz fb1_full_length_output.fq -t 12

however, we are only able to recover a tiny fraction of full length fragments :
Reads with two primers:	2.70%
Rescued reads:		0.00%
Unusable reads:		97.30%

When we start the run we are informed pychopper is using kit: PCS109, which is obviously wrong, but I can't seem to figure out if we need to or even can change it to DCS109. Do I have to provide a custom file of primers or configurations? Can you direct me to where this information is?

Thanks a lot. 
[report.pdf](https://github.com/epi2me-labs/pychopper/files/9196152/report.pdf)

Kalle

**Comment by rstewa03** [comment]
Any update on this? Is there any chance primers are being trimmed during base calling, affecting the identification of usable reads? 
Rachel

**Comment by nrhorner** [comment]
Hi @kallekarlhugo 
Please could you send me the `pychopper.tsv` output if possible?
I would also suggest contacting technical support - https://community.nanoporetech.com/support

**Comment by kallekarlhugo** [comment]
Hi, 
We rebasecalled all the data with SUP config since I posted this and got slightly better, but still terrible results. 

Is there any chance that something went wrong in the basecalling leading to trimming of the barcodes? I don't understand how it would be possible to have such a low proportion of reads with any primers at all. 

Thanks for your help
Kalle 
[cdna_classifier_report_SUP.pdf](https://github.com/epi2me-labs/pychopper/files/9459419/cdna_classifier_report_SUP.pdf)
[cdna_classifier_report_sup.zip](https://github.com/epi2me-labs/pychopper/files/9459424/cdna_classifier_report_sup.zip)

**Comment by nrhorner** [comment]
Thanks @kallekarlhugo  for those reports. While I'm digging into this, it might help me if you were able to send me some test here, if you're able: https://nanoporetech.box.com/s/8io1xeecvboxrwas5evct4m7etjdd8io

**Comment by kallekarlhugo** [comment]
absolutely, 

I can send a subset of reads to you, I think the link is broken now however.

**Comment by nrhorner** [comment]
Try this please: https://nanoporetech.ent.box.com/f/0b2efe38b64c447fafdee4e42d6ec25e

**Comment by kallekarlhugo** [comment]
Hi, I'm sorry it took me so long to get back, here are 10k reads, I hope that is enough. 
Thanks for your help

**Comment by nrhorner** [comment]
Hi, I'm sorry too for taking a while to get back. It does seem that most of the reads do not have the correct primer configurations. Sorry I can't be of more help, but I would recommend contacting ONT technical support if you haven't done already.

**Comment by nrhorner** [comment]
Closing as this does not seem to be an issue with Pychoper
