### ISSUE TITLE
Dual peaks on %GC plot from fastQC after running pychopper

### ISSUE THREAD

**Issue by chad388** [epi2me-labs/pychopper#30]
Hi,

I ran the latest version of pychopper on several direct cDNA-Seq datasets using the command line below:

`pychopper -U -y -k PCS111 -t 16 -r pychopper_report.pdf -u pychopper_unclassified.fastq -w pychopper_rescued.fastq fastq.gz pychopper.fastq.gz`

I ran fastqc on the fastq.gz files before and after running pychopper. The %GC plots of the data prior to running pychopper show normal distributions with a single peak. The %GC plots after running pychopper all show two distinct peaks. In some instances the two peaks are of similar height and in other instances they vary in height. 

Is it expected that there would be two distinct %GC peaks after running pychopper or could this be indicative of an issue with how I am running pychopper?

I attached the fastQC reports for the pre pychopper and post pychopper data in pdf format. The %GC plots are on page 5 of the pre pychopper report and on page 6 of the post pychopper report:

[HCT116KO_EV_DOX_Brep2_prePychopper_FastQC.Report.pdf](https://github.com/epi2me-labs/pychopper/files/12022996/HCT116KO_EV_DOX_Brep2_prePychopper_FastQC.Report.pdf)

[HCT116KO_EV_DOX_Brep2_postPychopper_FastQC.Report.pdf](https://github.com/epi2me-labs/pychopper/files/12022997/HCT116KO_EV_DOX_Brep2_postPychopper_FastQC.Report.pdf)

I also attached the pychopper.pdf report for this dataset:
[HCT116KO_EV_DOX_Brep2.pychopper_report.pdf](https://github.com/epi2me-labs/pychopper/files/12023071/HCT116KO_EV_DOX_Brep2.pychopper_report.pdf)

Thanks,

Chad

**Comment by nrhorner** [comment]
Closing due to lack of response

**Comment by umranyaman** [comment]
Hi, I have a similar issue, after running pychopper with correct cDNA kit, I started to get higher duplication levels, dual GC peak etc.. I don't get the duplication level or overrepresented sequences/higher duplication levels. 

Pre-pychopper:

[pre-pychopper_fastqc.pdf](https://github.com/user-attachments/files/18984373/pre-pychopper_fastqc.pdf)

Post-pychopper:

[post_pychopper_fastqc.pdf](https://github.com/user-attachments/files/18984388/post_pychopper_fastqc.pdf)

Pychopper report:

[pychopper_report.pdf](https://github.com/user-attachments/files/18984392/pychopper_report.pdf)

NanoPlot reports about readlength distribution:
`NanoPlot -t 30 --fastq barcode01_full_length_reads.fq --maxlength 40000 --plots dot --legacy hex`

![Image](https://github.com/user-attachments/assets/bbee56a6-6bc1-47c3-88a1-4377080f00c1)
![Image](https://github.com/user-attachments/assets/6a65b75e-d80e-4366-88d2-7837a4dc73ea)
![Image](https://github.com/user-attachments/assets/c3834ceb-72b5-4e27-bbf6-adfefb03cff0)
![Image](https://github.com/user-attachments/assets/b3a09761-e6a4-45f6-b7d1-d99fd2a67156)
![Image](https://github.com/user-attachments/assets/e7bfd8cf-bbc7-49ef-90f9-19e8422c8712)
![Image](https://github.com/user-attachments/assets/75bb6986-0b63-4738-afd4-9d71d0fb0505)

Thank you!
