### ISSUE TITLE
Installation problems since latest update

### ISSUE THREAD

**Issue by bernardo-heberle** [epi2me-labs/pychopper#31]
Hello,

I have not been able to install pychopper since the last update. I am using the command: `conda install -c nanoporetech -c conda-forge -c bioconda "nanoporetech::pychopper"`

I have tried several different solutions, but no luck so far.

The couple times I succeeded the executable on path was `cdna_classifier.py` instead of `pychopper`, which makes me think conda just installed an old version.

Best,
Bernardo

**Comment by bernardo-heberle** [comment]
It seems that some of the python packages used by Pychopper are not compatible with Python 3.11 (default on the latest conda version). I tried to solve the issue by installing Python 3.8 through conda, but it was still giving me the same error. Eventually I was able to install it using `mamba`. Here are the commands I used:

```
## Making sure libarchive-dev is available (Mamba needs it to install python)
apt-get update && apt-get -y install libarchive-dev

## Install miniconda ##
cd ~
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -bfp ~/conda
export PATH="~/conda/bin:$PATH"
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --add channels nanoporetech

## Install Mamba ##
conda install -c conda-forge --override-channels mamba

## Install Python 3.9 through Mamba ##
mamba install -y -c conda-forge --override-channels python=3.9

## Install Pychopper ##
mamba install -y -c nanoporetech pychopper=2.7.6
```

**Comment by bernardo-heberle** [comment]
It seems that some of the python packages used by Pychopper are not compatible with Python 3.11 (default on the latest conda version). I tried to solve the issue by installing Python 3.8 through conda, but it was still giving me the same error. Eventually I was able to install it using `mamba`. Here are the commands I used:

```
## Making sure libarchive-dev is available (Mamba needs it to install python)
apt-get update && apt-get -y install libarchive-dev

## Install miniconda ##
cd ~
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -bfp ~/conda
export PATH="~/conda/bin:$PATH"
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --add channels nanoporetech

## Install Mamba ##
conda install -c conda-forge --override-channels mamba

## Install Python 3.9 through Mamba ##
mamba install -y -c conda-forge --override-channels python=3.9

## Install Pychopper ##
mamba install -y -c nanoporetech pychopper=2.7.6
```

**Comment by Lujw9** [comment]
> It seems that some of the python packages used by Pychopper are not compatible with Python 3.11 (default on the latest conda version). I tried to solve the issue by installing Python 3.8 through conda, but it was still giving me the same error. Eventually I was able to install it using **mamba**. Here are the commands I used:
> 
> ```
> ## Making sure libarchive-dev is available (Mamba needs it to install python)
> apt-get update && apt-get -y install libarchive-dev
> 
> ## Install miniconda ##
> cd ~
> wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
> bash Miniconda3-latest-Linux-x86_64.sh -bfp ~/conda
> export PATH="~/conda/bin:$PATH"
> conda config --add channels bioconda
> conda config --add channels conda-forge
> conda config --add channels nanoporetech
> 
> ## Install Mamba ##
> conda install -c conda-forge --override-channels mamba
> 
> ## Install Python 3.9 through Mamba ##
> mamba install -y -c conda-forge --override-channels python=3.9
> 
> ## Install Pychopper ##
> mamba install -y -c nanoporetech pychopper=2.7.6
> ```

Really helpful! Appreciated!
