### ISSUE TITLE
Mapping of rescued reads

### ISSUE THREAD

**Issue by MartinezRuiz-Carlos** [epi2me-labs/pychopper#32]
Hi all, 

Apologies if this is a somewhat daft question, but from the documentation it is not completely clear to me. 
For aligning the reads after they have gone through PyChopper, should the full length and rescued set be aligned together? i.e. simply concatenating the fastqs? Do they need aligning separately with specific parameters? Or should they be kept out of most alignment pipelines?

My understanding is that the first option should be fine, but I wanted to double-check before going further.
Many thanks!

Best,
Carlos

**Comment by nrhorner** [comment]
Hi @MartinezRuiz-Carlos 

In most cases concatenating the full length and rescued reads would be the way to go. Having the rescued reads in a separate file gives you the option to exclude them from downstream analysis if they were found to have issues.

Thanks,

Neil

**Comment by MartinezRuiz-Carlos** [comment]
Perfect, thank you very much
