### ISSUE TITLE
Error when assigning kit "LSK114" to -k parameter

### ISSUE THREAD

**Issue by elhossary** [epi2me-labs/pychopper#34]
Hi,
I have a direct cDNA sample sequenced using SQK-LSK114 kit.
I encountered the following error when running Pychopper on conda
```
Traceback (most recent call last):
  File "~/miniconda3/envs/pychopper_env/bin/pychopper", line 10, in <module>
    sys.exit(main())
  File "~/miniconda3/envs/pychopper_env/lib/python3.8/site-packages/pychopper/scripts/pychopper.py", line 340, in main
    args.g = kits[args.k]["HMM"]
KeyError: 'LSK114'
```

How can I fix this? or Isn't this kit supported? any workarounds?

**Comment by nrhorner** [comment]
Hi @elhossary 

LSK114 is not currently supported. There will be an update out shortly to fix this. I will let you know.

**Comment by elhossary** [comment]
Thank you, looking forward for it

**Comment by elhossary** [comment]
LSK114 added, issue solved, thanks for the developers
