### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by VandaLovejoy** [epi2me-labs/pychopper#39]
Hello! I'm having an issue with the way pychopper is orienting my reads. 
This are my custom primers in the file custom_primers.fa : 
**>BanOne**
ATTGATGGTGCCTACAGT
**>SSP**
TTTCTGTTGGTGCTGATATTGCTGGG
 
and in primer_config.txt :
+:SSP,-BanOne|-:BanOne,-SSP

This is input sequence:
**TTTCTGTTGGTGCTGATATTGCTGGG**CTACTAAGTGGATGGAGTGGATGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTAGTAGAGACGGGGTTTCACCGTGTTAGCCAGGATGGTCTCGACCTCCTGCTCGTGATCCTCCCGCCTCAGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACCGCACCCAGCTGGATTCTTCTTAATTCTTTGTTTTTATTGTTTGACTCACCTGAGGTCTTTGGACTTTGCCTCTGAGCTGGCTTAAGGGCAATCCACCTTGTTCACTGGTCTGGAGTGAGAACAGTGTTGGGCTGGCTGGAGGAGTGGGGCTCTGTGCTCTCTTTTTTGAGAGTTTCTAAACGTCACTCTGCATGGTGAGGGGTGTGTCCTCTCCGCTGGGGAGGCCTGGCTTCCATTTCAGATTGCCTCCCTGGGACACCAGACCCTGTGCTGTGCTCCCTCAGAAGGACAGCCTTGACTGTCTCCCCTGCAGCAGTCCAGTTCTCCACTCCCACTGGGAGAAGGAGCAAAGGCTGGTGTCTTCAGGAGGCTCCTCTCCAGGCTGGGGCCAGGGAAGAGTGTCCTGTCACTGTCAGGATGTGTCCGGGGTGGGTGTGGCTGGGTTCTCAGGGTGAAGCTCGTCCATTTCTGGGATGGCAGCGGAAGCAGGCACTACACACACAGGCTTGGGGGCTGTCCCCATGCTTCCTAGCTGCCTGGCACTTTCTGGTGTTTCTGGCTAACTTTCTGGCCATGCCAGGAGTTGGTGGAAGGAGATCTCAGGCCGCAGCTTTGCTTTCCTGCTGGATGGTGTCCTGTGTGCTGGATTCCCCATGCTGTGTCCCCAGCAATATCAGCA

The command used:
pychopper \
  -b custom_primers.fa \
  -c primer_config.txt \
  -r ${output}/${filename}_report.pdf \
  -L 100 \
  -t 40 \
  -u ${output}/${filename}_unclassified.fastq \
  -w ${output}/${filename}_rescued.fastq \
  -S ${output}/${filename}_stats.txt \
  -m edlib \
  $file \
  ${output}/${filename}_full_length_output.fastq

In the classified file, this sequence is classified as the negative strand, although the sequence clearly starts with the SSP+.
Is there are way to fix this?

**Comment by nrhorner** [comment]
Hi @VandaLovejoy 

Wen I run with your data, Pychopper finds the following configuration.  And the BanOne -SSP is the one it choose as a segment, which is classed as  reverse orientation according to your primer_config.txt.

I don't really see the the --SSP in your read though. Will have a look at this later.

`SSP,BanOne,-SSP`

**Comment by nrhorner** [comment]
Hi @VandaLovejoy 

Sorry that I never followed up on this. Just ran again using the -A option to output the locations of the found adapter/primers sequences in your read, which gives the following:

```
readid  0       26      SSP     100     +
readid  17      35      BanOne  3       +
readid  851     867     SSP     4       -
```

As you can see, Pychopper identifies three sequences. But only the 2nd and 3rd make a valid pair (BanOne:-SSP) and this is the segment that is chosen. I hope this is clear to you.

**Comment by nrhorner** [comment]
Closing due to lack of response
