### ISSUE TITLE
Rescued reads

### ISSUE THREAD

**Issue by zhangqc723** [epi2me-labs/pychopper#40]
Hi there!
I was wondering what exactly the rescued reads would be.
Could you explain that to me?
Thanks in advance

**Comment by nrhorner** [comment]
Hi @zhangqc723 
Please see: https://github.com/epi2me-labs/pychopper#background
In summary, rescued reads are the subreads identified after splitting fused reads.

**Comment by zhangqc723** [comment]
Thanks for your patient reply!

**Comment by nrhorner** [comment]
You're welcome.
