### ISSUE TITLE
issue of alignment scores file

### ISSUE THREAD

**Issue by zhangqc723** [epi2me-labs/pychopper#41]
In my alignment scores file of pychopper, I find some same line (for example, Line1 and Line2), could you tell me why?
![Uploading image.png…]()

**Comment by zhangqc723** [comment]
5621486d-2446-40f0-ac9f-2fdd3ab199bf runid=c590fb43de99977d6e044d3c03311c335c20ad77 read=4305 ch=283 start_time=2023-08-01T21:45:18.473421+08:00 flow_cell_id=PAS00612 protocol_group_id=basecalled sample_id=20230801-HML231087-P4-PAS00612-fast parent_read_id=5621486d-2446-40f0-ac9f-2fdd3ab199bf basecall_model_version_id=dna_r10.4.1_e8.2_5khz_400bps_fast@v4.2.0	38	80	MyVNP	4	+
5621486d-2446-40f0-ac9f-2fdd3ab199bf runid=c590fb43de99977d6e044d3c03311c335c20ad77 read=4305 ch=283 start_time=2023-08-01T21:45:18.473421+08:00 flow_cell_id=PAS00612 protocol_group_id=basecalled sample_id=20230801-HML231087-P4-PAS00612-fast parent_read_id=5621486d-2446-40f0-ac9f-2fdd3ab199bf basecall_model_version_id=dna_r10.4.1_e8.2_5khz_400bps_fast@v4.2.0	38	80	MyVNP	4	+
5621486d-2446-40f0-ac9f-2fdd3ab199bf runid=c590fb43de99977d6e044d3c03311c335c20ad77 read=4305 ch=283 start_time=2023-08-01T21:45:18.473421+08:00 flow_cell_id=PAS00612 protocol_group_id=basecalled sample_id=20230801-HML231087-P4-PAS00612-fast parent_read_id=5621486d-2446-40f0-ac9f-2fdd3ab199bf basecall_model_version_id=dna_r10.4.1_e8.2_5khz_400bps_fast@v4.2.0	3363	3408	MyVNP	100	-

**Comment by zhangqc723** [comment]
Thanks, and I want to know if a reads not in the score file,  is there any primer present？

**Comment by zhangqc723** [comment]
@nrhorner 
When I get the output of pychopper, a reads does not appear in score file. But, I find it includes a primer.For example,
This my config file:
>MyVNP
TGAGAGACAAGATTGTTCGTGGACACGAGCATCAGCAGCATACGA
>MySSP
TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGATTGCGCAATG
This my reads from unclass_output:
TATGTTGTGGCCTGGTTCAGTTACGTATTTGTTTAGAGACAAGATTGTTCGTGGACACGAGCATCAGCCGCATAGGATTTTTTTTTTTTTTTTTTTTTTTAATTATTGAGATGGAGTCTCACTCTGTCGCCCAGGCTGGAGTGCAGTGGTGCAATCTCGGCTCACTGCAACTCCATCTCCTGGGTTCAAACAATTCTTGTGTCTCAGCCTACCAGTAGCCGGGATTACAGACTCGAGCCACCACGCCCAGCTAATTTTTTTTGTTGTTGTTTAAAGTAGAGACGGGTTTCACCACGTTGGCCAGGCTGGTCTCAAACTCCTGGCCTCAAGCGATCCGCCTGCCTCAGCCTCCCAAAGGGCTGGGATTACAGGCATGAGCCACCGTGCCGGTGTGTCCATGGGTTTTCTTTTATGCTTTAAGGAGGGTGATCTCAGCATGGAGCCCAAAGACTCTGGCACTTCCCTTTGTCCTTAAACCTCCTTGGCCAAATTTAGATTTAGTCTCTTTGAAGTGCTGGTTCACAATAGGATGTTTTTGTTGTTTTGTTAAAGTGGGAAAGAGCAATGAAAGAAAAAGTGAGAGAATTTTAACACTTGGGGCTGACACTGTCCAGGAAAACCATGGATGTATAGTGTGGGAGGGAGGAGGAGAAACTGACGTTTTTGAAGTTGGAAAGGTGTGGAGGTGGCATCTTAATTTAGTTGTGCAAAGAGGAAGTAAAAAGATTGACAATAAGACGTGTATAGATCAGAATAGAACGTTCTTAAGAGGGAAAGATGAAACATAAGCTGTTAATATTTTAATTCCCAGTCTGTTCTTAAAGATGAGAAAGCTTTGATCAGCAAGGCGAACATTCTAGAAAGAACTATTACGTGTATGTGGGGGGTGGGGAATGTGTGTATGCTGCATCTGTCAGACCTAGTCATTACAGTGTTCTGGGCGTAAGAACTCCGATTCTCATATTGCATTCTCTTCCATCACTTTATTTGGGGTGAAGCACATCGTCCTGTCAGTATCCACATTTGAAAAATAAAGAGATCCTGGCTAAATTGGGATCTCAAGTTCACTTAGTTTTTAGTAAGGGGAACTTGGTGAAAAATCGACTTGTGAGGTCTCCAGAAACACTTAATTGATAATGAGTCAAAAGGCATTACTCTTGGCATGTGAATATTGGATGTGAGCTAGAGGGTCAGTCAAATGCCTGTGGAGCCTGGATTCATGTTCTTTCCCGTTTGTCAGTAATCCTTTCTAATGTTCCAGTTCCCATGATGTTGATTTTAGTGGAATAAAACTTGAACCACTTAGTTATGATGTTGTTACTGTGTTGGGAACGCAGCAGCCACCAGACCACCAAGAGCAACTGTAGGTTGGGCTTGGTGGTGCTGGTTTAGTGTTGTGGCTGATGAGGTGTAACCCAGGAAATTTTTATTTTTGCTTTTAAAAAAACAACTCATCTGTGGTCATCTGTAAGTGGAATATTGGACTATAAGGACTCTAAGTTACCAAAAACATTTTGTGACTTAGCCTGAGGCTAACAGAAATAACTTCCCCCATGTTCAGATAGTTTAGGCATATCTGAGTTGGTGGAGGAAATGTGATCTGTTCCTAGCCCTATGTGCTAGGCAGGAGTGCCTGGGTATCCAAGAGTGAGTGAGAGGCCGGCGCGATGCATGCCTGTAATTCCAGCACTCTGGGAGGCGAAGCGCTTGAGCCCAAGAGTTCAAGACCAGCCTGGGCAACATGGGAAAAACCTGTCTCTACGAAAAAAAAAAAAAAAAAAAAAAAAAAAATCGTATGTGCTGATGCTCAGCAATTAGTAA
This is NCBI blast result:
![image](https://github.com/epi2me-labs/pychopper/assets/86176443/0216e487-1e2d-4160-a895-2858254e8108)
In fact, a myVNP primer is included by this reads. Could you tell me why didn't it appear in score file.

**Comment by nrhorner** [comment]
Hi @zhangqc723 I'm unable to replicate your problem with the identical entries in the AS score bed file output. Would you be able to hare a few reads that are affected please so I can debug. Also the command you used and the version of pychopper please

**Comment by nrhorner** [comment]
> Thanks, and I want to know if a reads not in the score file, is there any primer present？

Yes the scores file details the primer hits.
