### ISSUE TITLE
What does the numeric value of q mean?

### ISSUE THREAD

**Issue by mauricebarrett** [epi2me-labs/pychopper#44]
I am running a the command below

pychopper \
-t 20 \
-m edlib \
-b /mnt/2TB_SSD/databases/reference_data/primers/16s/custom_pimers.fas \
-c /mnt/2TB_SSD/databases/reference_data/primers/16s/primer_config.txt \
-r "$wor_dir"/fastq_files/pychopper/"$i"_report.pdf \
-L 100 \
-u "$wor_dir"/fastq_files/pychopper/"$i"_unclassified.fastq \
-w "$wor_dir"/fastq_files/pychopper/"$i"_rescued.fastq \
-S "$wor_dir"/fastq_files/pychopper/"$i"_stats.txt \
"$wor_dir"/fastq_files/demultiplexed/"$i".fastq \
"$wor_dir"/fastq_files/pychopper/"$i"_pychopper.fastq

From the auto-tuning I get "Best cutoff (q) value is 0.4545" What does this number mean?

**Comment by mauricebarrett** [comment]
@nrhorner 

Thanks for you prompt reply! And thanks for the explanation!

**Comment by nrhorner** [comment]
@mauricebarrett No problem.
