### ISSUE TITLE
Question about LSK114 primer sequences

### ISSUE THREAD

**Issue by cjops** [epi2me-labs/pychopper#45]
When using the `edlib` backend, I noticed that the primer sequences included in `LSK114_primers.fas` are very similar to the default `cDNA_SSP_VNP.fas`. In fact, as far as I can tell from the protocols for kit PCS109 and kit LSK114, these sequences haven't actually changed.

From Chemistry Technical Document July 8th, 2021:

![image11](https://github.com/epi2me-labs/pychopper/assets/108516/8bcee836-88f4-4562-90c8-30c0cc20fde4)

From Direct cDNA Sequencing V14 with SQK-LSK114 protocol:

![image14](https://github.com/epi2me-labs/pychopper/assets/108516/fe3b3338-be4a-4cc6-ae4a-4e59d2e88c4b)

In our data, generated with the new kit LSK114, the more complete version of the primers included in `cDNA_SSP_VNP.fas` leads to more usable reads. Was there any rationale behind using the shorter form of the primers for the new kit?

**Comment by nrhorner** [comment]
Hi @cjops 

These primer sequences were chosen from empirical observation when testing primer sequences on a limited number of datasets.  What recovery rate do you get with using both sets of primers?

**Comment by cjops** [comment]
I see, thanks! We've only done one run on a single flow cell so far, but this is with `cDNA_SSP_VNP.fas` (`pychopper -m edlib`, defaulting to PCS109):

![image2](https://github.com/epi2me-labs/pychopper/assets/108516/d82355d0-3c36-49b3-8773-10e35a04211d)

And this is with `LSK114_primers.fas` (`pychopper -m edlib -k LSK114`):

![image6](https://github.com/epi2me-labs/pychopper/assets/108516/ab6fdccb-74e7-4fad-b3d1-f72cd37efc65)

We're generating more data and I'll see which primer sequences perform best for that as well.

**Comment by nrhorner** [comment]
@cjops Thanks for sharing those, it's useful.

**Comment by nrhorner** [comment]
Closing due to lack of response
