### ISSUE TITLE
which kit parameter to choose for LSK109 kit

### ISSUE THREAD

**Issue by alexyfyf** [epi2me-labs/pychopper#47]
Hi team,

I'm wondering which parameter to choose for LSK109 kit.
Should I use LSK114 (to match the protocol) or PCS109 (to match chemisty)?

Thank you so much.

Alex

**Comment by nrhorner** [comment]
Hi @alexyfyf 

The adapters for LSK109 are not supported directly in Pychopper.

You can use custom primers/adapters in Pychopper by adding them to a file like this (LSK109.fa) - Pychopper expects two sequences with names VNP and SSP.
```
>VNP
TTTTTTTTTTTAATGTACTTCGTTCAGTTACGTATTGC-3
>SSP
GCAATACGTAACTGAACGAAGTACATT-3
```
Then you can use these adapters in pychopper with `-b LSK109.fa`

**Comment by nrhorner** [comment]
No response for a while so closing

**Comment by phpeters** [comment]
Dear @nrhorner ,

Thanks a ton for your work on pychopper! 
I have a question regarding the LSK109-SSP-sequence you mentioned. Isn't the sequence above a subsequence of the "adapter H"? Is there a reason you chose that? The SSP from kit DCS109 (and thus from LSK109) seems to be the same as in the LSK114 documents. 

Thanks for clarification and have a great weekend!
Philipp
