### ISSUE TITLE
trim out PCS111 UMI

### ISSUE THREAD

**Issue by camillaugolini-iit** [epi2me-labs/pychopper#49]
Hi, 

I would like to know if there is an option not only to detect the UMI from kit PCS111 and add them to the BAM tag, but if I can remove them directly from the fastq before the mapping.

Thanks a lot

Camilla

**Comment by nrhorner** [comment]
Hi @camillaugolini-iit 

The workflow does not currently trim adapters barcodes and UMIs from reads but is something we are considering adding soon.

Thanks,

Neil

**Comment by nrhorner** [comment]
Hi @camillaugolini-iit 

In my previous message I was on the repo for a different workflow, sorry for any confusion caused. It's not currently possible to remove the UMI from the read with Pychopper currently. We will consider adding that functionality

**Comment by nrhorner** [comment]
Closing due to lack of response
