### ISSUE TITLE
Reads which are still classified as reverse after using oychopper

### ISSUE THREAD

**Issue by senidr** [epi2me-labs/pychopper#5]
Hi im a little confused. So i have some reads that are still classified as reverse reads according to samtools flags and igv.
This is maybe 5% of reads and the rest is coming up as forward strand.
Does this mean the reverse strand is antisense reads?
Thanks

**Comment by cjw85** [comment]
That would be the correct interpretation of such reads. It indicates that the primers found in the reads are such that the RNA molecules aligns anti-parallel to the given reference.
