### ISSUE TITLE
One question about dorado basecalling trim option

### ISSUE THREAD

**Issue by dolittle007** [epi2me-labs/pychopper#52]
Hi team,

Since Pychopper uses primers (SSP, VNP) for classifying the reads, the primers should be kept during dorado basecalling.

While dorado `--trim` option takes as its argument one of the following values:

- `all`: This is the the same as the default behavior. Any detected adapters or primers will be trimmed, and if barcoding is enabled then any detected barcodes will be trimmed.
- `primers`: This will result in any detected adapters or primers being trimmed, but if barcoding is enabled the barcode sequences will not be trimmed.
- `adapters`: This will result in any detected adapters being trimmed, but primers will not be trimmed, and if barcoding is enabled then barcodes will not be trimmed either.
- `none`: This is the same as using the --no-trim option. Nothing will be trimmed.

According to the above description, `--trim adapters` should be used, am I right?

Thanks a lot in advance.

**Comment by nrhorner** [comment]
Hi @dolittle007 

I think you should be able to use `--trim adapters`  or `--no-trim` and still have your primer sequences in your reads.

Thanks

**Comment by dolittle007** [comment]
Hi @nrhorner, I have tried `--trim adapters`. It works well. Thanks a lot.
