### ISSUE TITLE
Primers/Adapters for kit SQK-LSK112 or SQK-NBD112-96

### ISSUE THREAD

**Issue by NikoLichi** [epi2me-labs/pychopper#56]
Hi there,

Similar to issue #47, I would like to use Pychopper for some sequences produced with the kit type SQK-NBD112-96, which, as far as I understood, belongs to the kit SQK-LSK112.

I already tried Pychopper but had this error:
`pychopper: error: argument -k: invalid choice: 'NBD112' (choose from 'PCS109', 'PCS110', 'PCS111', 'LSK114')`

Then, I looked for information/documentation to obtain the VNP and SSP sequences but did not find them.

Could someone please help me to know which sequences I need to specify in the `-k` argument?

All the best
Niko

**Comment by nrhorner** [comment]
Hi @NikoLichi 

I don't believe NBD112 is an official kit for cDNA, which is the data Pychopper deals with. Could you tell me more about what you are trying to achieve?

Thanks,

Neil

**Comment by nrhorner** [comment]
Closing from lack of response
