### ISSUE TITLE
Change umi pattern

### ISSUE THREAD

**Issue by passelma42** [epi2me-labs/pychopper#57]
Hi,

Is it possible to change the umi pattern if -U flag is issued.
We are using this pattern **TTTVVVVTTVVVVTTVVVVTTVVVVTTT** in our UMItagged amplicons.
If so we could use pychopper to get the correct tagged reads in our data.

**Comment by nrhorner** [comment]
Hi @passelma42 

TTTVVVVTTVVVVTTVVVVTTVVVVTTT is already the UMI pattern that is searched for with Pychopper. So you should be able to just use `-U` with your data. 

Neil

**Comment by nrhorner** [comment]
closing as no response
