### ISSUE TITLE
pychopper hanging without error message

### ISSUE THREAD

**Issue by dudududu12138** [epi2me-labs/pychopper#58]
Hello, I used pychopper(2.7.9) on my ONT reads but I met some troubles.  I installed pychopper on HPC which managed with slurm. I submitted the task and it ran successfully. But there were no results. The task just ran without any error or results. My ONT sample is about 120G without compressed. Is this too big to run your tool? And I have tried with different values of -B(10000,100000) but it was ineffective. All the output files are null. 
I just downsampled 200000 reads from the raw file and ran with the same code. Then it ran successfully and all the output files are correct. It is so strange.
Can you help me? Thank you very much!
This is my codes:
```
#! /bin/bash
#SBATCH -J pychopper
#SBATCH --partition=cpu
#SBATCH -n 40
sra=$1
pychopper -t 40 -Q 9  \
        -k PCS111 \
        -r $sra.pychopper_report.pdf \
        -u $sra.pychopper.unclassified.fq \
        -w $sra.pychopper.rescued.fq \
        -S $sra.pychopper.stats \
        -A $sra.pychopper.scores \
        $sra.fastq $sra.pychop.fastq
```

**Comment by nrhorner** [comment]
Hi @dudududu12138 

Could you post any output that was printed to the terminal please?

**Comment by nrhorner** [comment]
Hi @dudududu12138 

This could be related to an issue where the number of reads appears to be incorrectly counted at the initial threshold tuning step leading all reads to be used. Which might explain your issue. If you post the output of the program, I will be able to tell if that is the issue.

**Comment by dudududu12138** [comment]
> Hi @dudududu12138
> 
> This could be related to an issue where the number of reads appears to be incorrectly counted at the initial threshold tuning step leading all reads to be used. Which might explain your issue. If you post the output of the program, I will be able to tell if that is the issue.

Hi,sorry for the late reply. I split my raw reads into several subfiles and ran pychopper on the small files.Then it works.I thought there might be some problem at the multiprocessing step and you can check it.

**Comment by nrhorner** [comment]
HI @dudududu12138 
Would you be able to paste the output of Pychopper please?

**Comment by dudududu12138** [comment]
> The task just ran without any error or results.

The task just ran without any error or results. Only if I cut the big file into small files and ran them separately, it will report correct results. Just like below:
```
001.pychopper_report.pdf
001.pychopper.rescued.fq
001.pychopper.scores
001.pychopper.stats
001.pychopper.unclassified.fq
```

**Comment by nrhorner** [comment]
So you don't see anything printed to the screen?

**Comment by nrhorner** [comment]
Closing due to lack of response.
