### ISSUE TITLE
"no reverse complement" warnings

### ISSUE THREAD

**Issue by omarkr8** [epi2me-labs/pychopper#59]
Hi, 

using pychopper as part of a pipeline elsewhere, it seems to process the fastqs fine, but will always come up with the same "warning" for each sample in a batch.
read-out might look like :
_Using kit: PCS109
Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
WARNING: No reverse complement for R found, returning argument.WARNING: No reverse complement for R found, returning argument.WARNING: No reverse complement for W found, returning argument.WARNING: No reverse complement for K found, returning argument.Counting fastq records in input file: shb_results/quality_filtering/barcode13_A_R1.fastq_

so in particular the "WARNING: No reverse complement for R found, returning argument." is troubling me. seems to imply there are Rs,Ws, and Ks in my sequence? i think for another experiment it was a separate set of letters. my gut feeling is that it's to do with file names somehow getting passed as sequence. unsure if its a pychopper issue or I concatenated my fastq.gzs wrong. 

in any case, would be good to know what triggers this.

**Comment by omarkr8** [comment]
i am unsure. pychopper is used as part of the Natrix2 pipeline (https://github.com/dbeisser/Natrix2/tree/dev), which is where im getting these errors.

could you explain what you mean by base_complement not being in the workflow?

**Comment by nrhorner** [comment]
Hi @omarkr8 

The error message you are getting appears to be coming from `pychopper/seq_utils.base_complement` which is not actually called by any part of the pychopper code (and shouldn't actually be in the the repository). So I'm unsure why you are getting this warning message.

What version of pychopper are you using?

**Comment by omarkr8** [comment]
from _init_.py it says version 2.7.2.

my guess is the devs from the pipeline im using just havent updated the tools.

**Comment by nrhorner** [comment]
Yes I would recommend updating to 2.7.9

**Comment by nrhorner** [comment]
Closing from lack of response Please open another ticket if this issue arises again
