### ISSUE TITLE
ImportError: cannot import name seq_utils

### ISSUE THREAD

**Issue by Catherine9826** [epi2me-labs/pychopper#6]
When I first use the pychopper , i met a problems as follows:
Traceback (most recent call last):
  File "/home/zf/install/miniconda2/bin/pychopper", line 7, in <module>
    from pychopper.scripts.pychopper import main
  File "/home/zf/install/miniconda2/lib/python2.7/site-packages/pychopper/scripts/pychopper.py", line 14, in <module>
    from pychopper import seq_utils as seu
ImportError: cannot import name seq_utils

Whether there is something wrong with my download?

**Comment by nrhorner** [comment]
Hi @Catherine9826 Can you try with  miniconda3 please?

**Comment by Catherine9826** [comment]
> 

Thanks for your answering, after i use miniconda3 , it comes a new problem:
Traceback (most recent call last):
      File "/home/spider/soft/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 704, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "/home/spider/soft/miniconda3/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch/current_repodata.json

**Comment by nrhorner** [comment]
please could you send me the command that you have used

**Comment by Catherine9826** [comment]
> please could you send me the command that you have used

I use two methods to download the pychopper ,one is the command below ,one is the installation package. Both methods don't work.
conda install -c epi2melabs -c conda-forge -c bioconda "epi2melabs::pychopper"

**Comment by nrhorner** [comment]
There's something wrong with your conda setup. It's trying to load the conda index from https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch/current_repodata.json, which does not exist.

This page has information about managing conda channels: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

**Comment by Catherine9826** [comment]
> There's something wrong with your conda setup. It's trying to load the conda index from https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch/current_repodata.json, which does not exist.
> 
> This page has information about managing conda channels: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

Thank you so much.
