### ISSUE TITLE
Trim adapter

### ISSUE THREAD

**Issue by lalalagartija** [epi2me-labs/pychopper#60]
Hi, 

pychopper seems very effective to identify adapters but is unable to remove them on the contrary of what is said here : https://github.com/epi2me-labs/pychopper/issues/25

Here is the line I used : 
`
pychopper -m edlib -b $adapter  -r pychopper_report_${outname}.pdf -S pychopper_report_${outname}.stats -t $THREADS -u ${outname}_pychopper.fastq  $reads ${outname}_classified_pychopper.fastq `

Is there any way to remove adapters or at least know the positions where they were found ? 

Thank you in advance,

**Comment by nrhorner** [comment]
Hi @lalalagartija 

Adapters should be trimmed if the correct kit is specified. What kit are you using?

**Comment by nrhorner** [comment]
Closing due to lack of response
