### ISSUE TITLE
Which -k kit should be chosen for the PCR-cDNA Sequencing Kit (SQK-PCB114.24) and PCR Barcoding Kit (PBC096)?

### ISSUE THREAD

**Issue by biochristmas** [epi2me-labs/pychopper#61]
Hi, for ONT RNA-Seq, eighteen cDNA libraries were built using the PCR-cDNA Sequencing Kit (SQK-PCB114.24) and PCR Barcoding Kit (PBC096). Which pychopper parameter (-k) should I use to identify full-length transcripts? Thank you.

**Comment by nrhorner** [comment]
Hi @biochristmas 

You can use `-k PCS111`

**Comment by nrhorner** [comment]
Closing due to lack of response
