### ISSUE TITLE
The full-length sequences are shorter than the derRNA sequences.

### ISSUE THREAD

**Issue by biochristmas** [epi2me-labs/pychopper#62]
I ran the command to identify full-length transcripts: pychopper -k PCS111 -r CK.report.pdf -u CK.unclassified.fq -w.rescued.fq CK.derRNA.fastq CK.full_length_output.fq. I conducted length statistics on the input sequences (CK.derRNA.fastq), with a minimum length of 500bp. The full-length transcripts (CK.full_length_output.fq) have a minimum length of 50bp. Why are the sequences derived from the input sequence (full-length transcript sequences) shorter instead?

**Comment by nrhorner** [comment]
Hi @biochristmas 

So you are finding that the minimum length of the input reads are 500bp, while that of the processed reads is 50bp?

This is likely due to some of the reads being chimeric and split into multiple, smaller subreads.

**Comment by nrhorner** [comment]
Closing due to no response
