### ISSUE TITLE
pychopper with Native Barcoding Kit (SQK-NBD114)?

### ISSUE THREAD

**Issue by jylee43** [epi2me-labs/pychopper#63]
Hi, 

I got Nanopore full-length transcriptome data from a **PromethION 2 Solo** machine. 
For the library preparation, we used the **Native Barcoding Kit 24 V14 (SQK-NBD114.24)**. 

**Can I use pychopper for NBD kits?** 

When I checked ['primer_data' directory and available primer lists in pychopper](https://github.com/epi2me-labs/pychopper/tree/master/pychopper/primer_data), the Native Barcoding Kit (NBD) are not included in pychopper. 

I have tried to use pychopper for my barcoding sequences, but I haven’t succeeded so far. 

It looks like pychopper was developed mainly for primers from cDNA or single strand DNA with PCR. However, NBD kits use dsDNA as an input and PCR process is not included. 

Is it still possible to use pychopper for the different library preparation technique by NBD kit?

I also tried dorado for trimming step, but still like to use pychopper to **1) trim barcode flanking sequences, 2) get +/- strand information, and 3) use full-length sequences for further analysis**. 

I have tried several ways to use pychopper, and all my results have 
A) zero or few sequences with +/- strand detection, and 
B) classification : 100% reads are unusable (so almost sequences were in unclassified.fq file). 

I will explain what I did and got here. 

**Trial 1.** In the beginning, I just ran pychopper with the existing primers (although I later knew there aren't that much overlapping sequences between primers in pychopper and my barcoding sequences). 
`pychopper -k PCS109`
`pychopper -k PCS110`
`pychopper -k PCS111`
`pychopper -k LSK114`
And as you can expect, pychopper barely detected +/- strands, all reads were unclassified, and I didn't get full-length sequences. 

**Trial 2.** I made a custom fasta file with my barcode flanking sequences for NB01 barcode and use '-b and -m' options. 

Note: You can find [the NBD barcode sequences from the official NanopreTech website](https://community.nanoporetech.com/technical_documents/chemistry-technical-document/v/chtd_500_v1_revaq_07jul2016/barcode-sequences).

> Barcode flanking sequences:
> Forward sequence: 5' - AAGGTTAA - barcode - CAGCACCT - 3'
> Reverse sequence: 5' - GGTGCTG - barcode - TTAACCTTAGCAAT - 3'

Note. In this post, I will only talk about NB01 (barcode 01) for an example. 
> NB01_Forward sequence: CACAAAGACACCGACAACTTTCTT
> NB01_Reverse sequence: AAGAAAGTTGTCGGTGTCTTTGTG

This is a custom primer file I used: NBD_primers.fas
\>BFS_NB01-F
AAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCT
\>BFS_NB01-R
GGTGCTGAAGAAAGTTGTCGGTGTCTTTGTGTTAACCTTAGCAAT

`pychopper -b NBD_primers.fas -m edlib`

Still not better results....

**Trial 3.** After I compared [protocols between NBD114](https://community.nanoporetech.com/docs/prepare/library_prep_protocols/ligation-sequencing-amplicons-native-barcoding-v14-sqk-nbd114-24/v/nba_9168_v114_revm_15sep2022/overview-of-the-protocol?devices=minion) and PCS109/110/111, I thought that I may use different sequences to use pychopper. 

For example, NBD114 has forward and reverse barcoding flanking sequences, but actually they are complementary. So instead of using forward and reverse sequences separately, I used the forward sequence only by using pychopper default options. 

At the same time, I also replaced LSK114_primers.fas with NBD114 sequences. I wanted pychopper treat my BFS like LSK114 primers, since I don't fully understand `-b and -m` options. 

\> VNP # actually from BFS_NB01-F
AAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCT
\>SSP
AAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCT

`pychopper -k LSK114`

Then I also got the similar result like before. # read with strand +/- information : 7 /18 reads among 1910 reads. It shows that pychopper barely detects my 'primers' or classifies them.

Before I simply move to another tool, I would like to understand the origin of my issues and the the application or limitations of pychopper. 

Any comments will be appreciated! Thank your help in advance!

**Comment by nrhorner** [comment]
Hi @jylee43 

Native barcoding kits are not supported with pychopper as, like you suggested, it was designed for processing transcript data.  Also, you say you want to get the strand information, but I'm not sure what you mean by that as your data is dsDNA and each fragment will have the same adapters ligated to each end, wil they not?

**Comment by jylee43** [comment]
Hi @nrhorner 

Thank you for your quick reply!

> Native barcoding kits are not supported with pychopper as, like you suggested, it was designed for processing transcript data. 
I am happy to know that I don't need to try pychopper anymore, since it does not support Native Barcoding Kits. 

> Also, you say you want to get the strand information, but I'm not sure what you mean by that as your data is dsDNA and each fragment will have the same adapters ligated to each end, will they not?
Right, as you say each fragment will have the same adapters ligated to each end. So we cannot get the strand information based on the primer/adapter sequences. I didn't fully understand the protocol of NBD kit and it looks like I got confused. Thanks to your comments, it looks clear for me. 

I appreciate your feedback! Now my questions are solved.
