### ISSUE TITLE
`import imp` has been removed from Python 3.12

### ISSUE THREAD

**Issue by a-detiste** [epi2me-labs/pychopper#66]
On Debian we have python3-zombie-imp, but that's not a long-term solution.

 # zombie-imp
 .
 ~~A particularly mischevious act of necromancy. That is,~~
 A copy of the `imp` module that was removed in Python 3.12.
 .
 Don't use this, it'll probably trick and bite you.

**Comment by cjw85** [comment]
As far as I can see, `imp` is used only in the scripts for creating docs, and not the pychopper package itself.
