### ISSUE TITLE
High number of unclassified reads (kit DCS109) even with rescue mode (-x)

### ISSUE THREAD

**Issue by camillaugolini-iit** [epi2me-labs/pychopper#7]
Hi @bsipos,

I've been running pychopper on a direct-cDNA dataset obtained with kit DCS109. As described in the completed issues, I ran pychopper a first time obtaining the 38% of classified reads and then rerun it on the unclassified reads in rescue mode, obtaining 1% of classified reads. 

I tried rebasecalling reads with the option --trim_strategy 'none' in guppy basecaller and rerun pychopper but obtained no improvements.
I also tried fine tuning the -q parameter and changing the pychopper mode from 'phmm' to 'edlib', but the results still show a high number of unclassified reads. However, the report of the first run shows that more than 1 million unclassified reads were found to have two hits. 

Could you please help me to solve this issue or to identify if the problem may be in the library prep or in the downstream analysis?

Thanks a lot,

Camilla

**Comment by nrhorner** [comment]
Hi @camillaugolini-iit 
Sorry for the very late reply. If your are still having issues with this, I'd be glad to look at some of your data

**Comment by nrhorner** [comment]
Closed due to lack of response
