### ISSUE TITLE
Clarification on PCS114 vs. PCS111 Primer Configuration in Pychopper

### ISSUE THREAD

**Issue by bernardo-heberle** [epi2me-labs/pychopper#70]
Hi,

I noticed that the latest Pychopper update includes an option for the PCS114 kit. Could you clarify if there is any actual difference in the primer configuration or the underlying code when selecting PCS114 compared to PCS111?

Based on previous discussions in this repository, I was under the impression that PCS111 and PCS114 used the same primers, and that there was no difference in running Pychopper for either. Has something changed, or was the PCS114 option added primarily for user convenience?

I ask because I’ve processed over 100 samples using the PCS111 setting with Pychopper version 2.7.9 in my pipeline. If there’s a significant advantage to using PCS114, I’d consider re-running the samples or updating the Pychopper version for future sequencing batches.

Best,
Bernardo

**Comment by nrhorner** [comment]
Hi @bernardo-heberle PCS114, 

As you've suggested, was added for convenience. The same primers are used as for PCS111.

Cheers,

Neil

**Comment by bernardo-heberle** [comment]
Cool, thank you!
