### ISSUE TITLE
random hexamers for direct-cdna sequencing

### ISSUE THREAD

**Issue by evihadj** [epi2me-labs/pychopper#8]
Hello,

I used random hexamers instead of the VNP since most of my transcripts are not polyadenylated. I still used SSP though.
How can I use pychopper in this case?

Thanks a lot,
Evi

**Comment by nrhorner** [comment]
Hi @evihadj and sorry for the late reply. 
Pychopper will not be able to process your reads as it needs two defined primers in order to determine read segments.
Thanks,

Neil
