### ISSUE TITLE
Can I use pychopper after an adaptive sampling run?

### ISSUE THREAD

**Issue by smf96** [epi2me-labs/pychopper#9]
Hello,

In a normal SQK-PCS111 run we find ~80% are full length reads but when we apply adaptive sampling to enrich for our targets, pychopper says there is only 20% full-length reads. 

I understand applying adaptive sampling to cDNA runs is quite unusual so am wondering if you've come across this before? Do you know if turning adaptive sampling on means that the primers are trimmed away in MinKnow's fastq output?

Many thanks!

All the best,

Sarah

**Comment by callumparr** [comment]
Adaptive sampling should not trim primers/adapters/linkers. 

But now your FASTQ is a mix of enriched and depleted sequences? It would make perfect sense the % full length as judged by containing both head and tail would reduce as you've actively kicked out reads before the molecule end. I believe these are still basecalled and if they pass Q-score filtering they will be in your PASS fastq file. Perhaps it would make more sense to filter your FASTQ based on an initial mapping to your target sequences. After this run pychopper to orientate your reads. 

Or filter by length as the rejected reads should be shorter.

Out of interest what kind of enrichment did you see? Given the basecall speed and the average length of a cDNA, I would have thought it would be challenging to get meaningful enrichment in terms of Gbps sequenced.

**Comment by cjw85** [comment]
Hi @smf96.

Callum is perfectly correct and your observation of a low percentag of full length reads is expected as the sequencer does not seggregate rejected reads in its ouput. Please raise this as a feature request in the Nanopore Community. (I've suggested this several times but requests from customers always carry more weight 😉 )
